// Automatically generated type file. 
export type UtilsLayerDef = Partial<Record<
  'FillAntialias' |
  'FillOpacity' |
  'FillColor' |
  'FillOutlineColor' |
  'FillTranslate' |
  'FillTranslateAnchor' |
  'FillPattern' |
  'FillEmissiveStrength' |
  'FillZOffset' |
  'FillExtrusionOpacity' |
  'FillExtrusionColor' |
  'FillExtrusionTranslate' |
  'FillExtrusionTranslateAnchor' |
  'FillExtrusionPattern' |
  'FillExtrusionHeight' |
  'FillExtrusionBase' |
  'FillExtrusionHeightAlignment' |
  'FillExtrusionBaseAlignment' |
  'FillExtrusionVerticalGradient' |
  'FillExtrusionAmbientOcclusionIntensity' |
  'FillExtrusionAmbientOcclusionRadius' |
  'FillExtrusionAmbientOcclusionWallRadius' |
  'FillExtrusionAmbientOcclusionGroundRadius' |
  'FillExtrusionAmbientOcclusionGroundAttenuation' |
  'FillExtrusionFloodLightColor' |
  'FillExtrusionFloodLightIntensity' |
  'FillExtrusionFloodLightWallRadius' |
  'FillExtrusionFloodLightGroundRadius' |
  'FillExtrusionFloodLightGroundAttenuation' |
  'FillExtrusionVerticalScale' |
  'FillExtrusionRoundedRoof' |
  'FillExtrusionCutoffFadeRange' |
  'FillExtrusionEmissiveStrength' |
  'FillExtrusionLineWidth' |
  'FillExtrusionCastShadows' |
  'LineOpacity' |
  'LineColor' |
  'LineTranslate' |
  'LineTranslateAnchor' |
  'LineWidth' |
  'LineGapWidth' |
  'LineOffset' |
  'LineBlur' |
  'LineDasharray' |
  'LinePattern' |
  'LineGradient' |
  'LineTrimOffset' |
  'LineTrimFadeRange' |
  'LineTrimColor' |
  'LineEmissiveStrength' |
  'LineBorderWidth' |
  'LineBorderColor' |
  'LineOcclusionOpacity' |
  'CircleRadius' |
  'CircleColor' |
  'CircleBlur' |
  'CircleOpacity' |
  'CircleTranslate' |
  'CircleTranslateAnchor' |
  'CirclePitchScale' |
  'CirclePitchAlignment' |
  'CircleStrokeWidth' |
  'CircleStrokeColor' |
  'CircleStrokeOpacity' |
  'CircleEmissiveStrength' |
  'HeatmapRadius' |
  'HeatmapWeight' |
  'HeatmapIntensity' |
  'HeatmapColor' |
  'HeatmapOpacity' |
  'IconOpacity' |
  'IconOcclusionOpacity' |
  'IconEmissiveStrength' |
  'TextEmissiveStrength' |
  'IconColor' |
  'IconHaloColor' |
  'IconHaloWidth' |
  'IconHaloBlur' |
  'IconTranslate' |
  'IconTranslateAnchor' |
  'IconImageCrossFade' |
  'TextOpacity' |
  'TextOcclusionOpacity' |
  'TextColor' |
  'TextHaloColor' |
  'TextHaloWidth' |
  'TextHaloBlur' |
  'TextTranslate' |
  'TextTranslateAnchor' |
  'IconColorSaturation' |
  'IconColorContrast' |
  'IconColorBrightnessMin' |
  'IconColorBrightnessMax' |
  'SymbolZOffset' |
  'RasterOpacity' |
  'RasterColor' |
  'RasterColorMix' |
  'RasterColorRange' |
  'RasterHueRotate' |
  'RasterBrightnessMin' |
  'RasterBrightnessMax' |
  'RasterSaturation' |
  'RasterContrast' |
  'RasterResampling' |
  'RasterFadeDuration' |
  'RasterEmissiveStrength' |
  'RasterArrayBand' |
  'RasterElevation' |
  'RasterParticleArrayBand' |
  'RasterParticleCount' |
  'RasterParticleColor' |
  'RasterParticleMaxSpeed' |
  'RasterParticleSpeedFactor' |
  'RasterParticleFadeOpacityFactor' |
  'RasterParticleResetRateFactor' |
  'RasterParticleElevation' |
  'HillshadeIlluminationDirection' |
  'HillshadeIlluminationAnchor' |
  'HillshadeExaggeration' |
  'HillshadeShadowColor' |
  'HillshadeHighlightColor' |
  'HillshadeAccentColor' |
  'HillshadeEmissiveStrength' |
  'BackgroundPitchAlignment' |
  'BackgroundColor' |
  'BackgroundPattern' |
  'BackgroundOpacity' |
  'BackgroundEmissiveStrength' |
  'SkyType' |
  'SkyAtmosphereSun' |
  'SkyAtmosphereSunIntensity' |
  'SkyGradientCenter' |
  'SkyGradientRadius' |
  'SkyGradient' |
  'SkyAtmosphereHaloColor' |
  'SkyAtmosphereColor' |
  'SkyOpacity' |
  'ModelOpacity' |
  'ModelRotation' |
  'ModelScale' |
  'ModelTranslation' |
  'ModelColor' |
  'ModelColorMixIntensity' |
  'ModelType' |
  'ModelCastShadows' |
  'ModelReceiveShadows' |
  'ModelAmbientOcclusionIntensity' |
  'ModelEmissiveStrength' |
  'ModelRoughness' |
  'ModelHeightBasedEmissiveStrengthMultiplier' |
  'ModelCutoffFadeRange' |
  'ModelFrontCutoff' |
  'Visibility' |
  'ModelId' |
  'ClipLayerTypes' |
  'ClipLayerScope' |
  'FillSortKey' |
  'FillElevationReference' |
  'CircleSortKey' |
  'FillExtrusionEdgeRadius' |
  'LineCap' |
  'LineJoin' |
  'LineMiterLimit' |
  'LineRoundLimit' |
  'LineSortKey' |
  'LineZOffset' |
  'LineElevationReference' |
  'LineCrossSlope' |
  'LineWidthUnit' |
  'SymbolPlacement' |
  'SymbolSpacing' |
  'SymbolAvoidEdges' |
  'SymbolSortKey' |
  'SymbolZOrder' |
  'SymbolZElevate' |
  'SymbolElevationReference' |
  'IconAllowOverlap' |
  'IconIgnorePlacement' |
  'IconOptional' |
  'IconRotationAlignment' |
  'IconSize' |
  'IconSizeScaleRange' |
  'IconTextFit' |
  'IconTextFitPadding' |
  'IconImage' |
  'IconRotate' |
  'IconPadding' |
  'IconKeepUpright' |
  'IconOffset' |
  'IconAnchor' |
  'IconPitchAlignment' |
  'TextPitchAlignment' |
  'TextRotationAlignment' |
  'TextField' |
  'TextFont' |
  'TextSize' |
  'TextSizeScaleRange' |
  'TextMaxWidth' |
  'TextLineHeight' |
  'TextLetterSpacing' |
  'TextJustify' |
  'TextRadialOffset' |
  'TextVariableAnchor' |
  'TextAnchor' |
  'TextMaxAngle' |
  'TextWritingMode' |
  'TextRotate' |
  'TextPadding' |
  'TextKeepUpright' |
  'TextTransform' |
  'TextOffset' |
  'TextAllowOverlap' |
  'TextIgnorePlacement' |
  'TextOptional' |
  'fill-antialias' |
  'fill-opacity' |
  'fill-color' |
  'fill-outline-color' |
  'fill-translate' |
  'fill-translate-anchor' |
  'fill-pattern' |
  'fill-emissive-strength' |
  'fill-z-offset' |
  'fill-extrusion-opacity' |
  'fill-extrusion-color' |
  'fill-extrusion-translate' |
  'fill-extrusion-translate-anchor' |
  'fill-extrusion-pattern' |
  'fill-extrusion-height' |
  'fill-extrusion-base' |
  'fill-extrusion-height-alignment' |
  'fill-extrusion-base-alignment' |
  'fill-extrusion-vertical-gradient' |
  'fill-extrusion-ambient-occlusion-intensity' |
  'fill-extrusion-ambient-occlusion-radius' |
  'fill-extrusion-ambient-occlusion-wall-radius' |
  'fill-extrusion-ambient-occlusion-ground-radius' |
  'fill-extrusion-ambient-occlusion-ground-attenuation' |
  'fill-extrusion-flood-light-color' |
  'fill-extrusion-flood-light-intensity' |
  'fill-extrusion-flood-light-wall-radius' |
  'fill-extrusion-flood-light-ground-radius' |
  'fill-extrusion-flood-light-ground-attenuation' |
  'fill-extrusion-vertical-scale' |
  'fill-extrusion-rounded-roof' |
  'fill-extrusion-cutoff-fade-range' |
  'fill-extrusion-emissive-strength' |
  'fill-extrusion-line-width' |
  'fill-extrusion-cast-shadows' |
  'line-opacity' |
  'line-color' |
  'line-translate' |
  'line-translate-anchor' |
  'line-width' |
  'line-gap-width' |
  'line-offset' |
  'line-blur' |
  'line-dasharray' |
  'line-pattern' |
  'line-gradient' |
  'line-trim-offset' |
  'line-trim-fade-range' |
  'line-trim-color' |
  'line-emissive-strength' |
  'line-border-width' |
  'line-border-color' |
  'line-occlusion-opacity' |
  'circle-radius' |
  'circle-color' |
  'circle-blur' |
  'circle-opacity' |
  'circle-translate' |
  'circle-translate-anchor' |
  'circle-pitch-scale' |
  'circle-pitch-alignment' |
  'circle-stroke-width' |
  'circle-stroke-color' |
  'circle-stroke-opacity' |
  'circle-emissive-strength' |
  'heatmap-radius' |
  'heatmap-weight' |
  'heatmap-intensity' |
  'heatmap-color' |
  'heatmap-opacity' |
  'icon-opacity' |
  'icon-occlusion-opacity' |
  'icon-emissive-strength' |
  'text-emissive-strength' |
  'icon-color' |
  'icon-halo-color' |
  'icon-halo-width' |
  'icon-halo-blur' |
  'icon-translate' |
  'icon-translate-anchor' |
  'icon-image-cross-fade' |
  'text-opacity' |
  'text-occlusion-opacity' |
  'text-color' |
  'text-halo-color' |
  'text-halo-width' |
  'text-halo-blur' |
  'text-translate' |
  'text-translate-anchor' |
  'icon-color-saturation' |
  'icon-color-contrast' |
  'icon-color-brightness-min' |
  'icon-color-brightness-max' |
  'symbol-z-offset' |
  'raster-opacity' |
  'raster-color' |
  'raster-color-mix' |
  'raster-color-range' |
  'raster-hue-rotate' |
  'raster-brightness-min' |
  'raster-brightness-max' |
  'raster-saturation' |
  'raster-contrast' |
  'raster-resampling' |
  'raster-fade-duration' |
  'raster-emissive-strength' |
  'raster-array-band' |
  'raster-elevation' |
  'raster-particle-array-band' |
  'raster-particle-count' |
  'raster-particle-color' |
  'raster-particle-max-speed' |
  'raster-particle-speed-factor' |
  'raster-particle-fade-opacity-factor' |
  'raster-particle-reset-rate-factor' |
  'raster-particle-elevation' |
  'hillshade-illumination-direction' |
  'hillshade-illumination-anchor' |
  'hillshade-exaggeration' |
  'hillshade-shadow-color' |
  'hillshade-highlight-color' |
  'hillshade-accent-color' |
  'hillshade-emissive-strength' |
  'background-pitch-alignment' |
  'background-color' |
  'background-pattern' |
  'background-opacity' |
  'background-emissive-strength' |
  'sky-type' |
  'sky-atmosphere-sun' |
  'sky-atmosphere-sun-intensity' |
  'sky-gradient-center' |
  'sky-gradient-radius' |
  'sky-gradient' |
  'sky-atmosphere-halo-color' |
  'sky-atmosphere-color' |
  'sky-opacity' |
  'model-opacity' |
  'model-rotation' |
  'model-scale' |
  'model-translation' |
  'model-color' |
  'model-color-mix-intensity' |
  'model-type' |
  'model-cast-shadows' |
  'model-receive-shadows' |
  'model-ambient-occlusion-intensity' |
  'model-emissive-strength' |
  'model-roughness' |
  'model-height-based-emissive-strength-multiplier' |
  'model-cutoff-fade-range' |
  'model-front-cutoff' |
  'visibility' |
  'model-id' |
  'clip-layer-types' |
  'clip-layer-scope' |
  'fill-sort-key' |
  'fill-elevation-reference' |
  'circle-sort-key' |
  'fill-extrusion-edge-radius' |
  'line-cap' |
  'line-join' |
  'line-miter-limit' |
  'line-round-limit' |
  'line-sort-key' |
  'line-z-offset' |
  'line-elevation-reference' |
  'line-cross-slope' |
  'line-width-unit' |
  'symbol-placement' |
  'symbol-spacing' |
  'symbol-avoid-edges' |
  'symbol-sort-key' |
  'symbol-z-order' |
  'symbol-z-elevate' |
  'symbol-elevation-reference' |
  'icon-allow-overlap' |
  'icon-ignore-placement' |
  'icon-optional' |
  'icon-rotation-alignment' |
  'icon-size' |
  'icon-size-scale-range' |
  'icon-text-fit' |
  'icon-text-fit-padding' |
  'icon-image' |
  'icon-rotate' |
  'icon-padding' |
  'icon-keep-upright' |
  'icon-offset' |
  'icon-anchor' |
  'icon-pitch-alignment' |
  'text-pitch-alignment' |
  'text-rotation-alignment' |
  'text-field' |
  'text-font' |
  'text-size' |
  'text-size-scale-range' |
  'text-max-width' |
  'text-line-height' |
  'text-letter-spacing' |
  'text-justify' |
  'text-radial-offset' |
  'text-variable-anchor' |
  'text-anchor' |
  'text-max-angle' |
  'text-writing-mode' |
  'text-rotate' |
  'text-padding' |
  'text-keep-upright' |
  'text-transform' |
  'text-offset' |
  'text-allow-overlap' |
  'text-ignore-placement' |
  'text-optional' , any>>
